// .                 ...................                               ...           .   ..............  ................................,;:::;;;,.................
//                                                                     ....   ...........................................................,:::;;:;,.................
//                       .  ...........                               ..,;'...',,;;:;;,,,;;:ccccc:::;;,,'''...........................  .';::;;;;,.................
//    .....................................                   ..'',,,;ccc:::llccloooollccclooolloodddddooll:;,''.........................';::;;;;,.................
// '........................................ ...............';:c::;,;col:;;:c::::::::cllc::::cclllloddolloollllll:,.......            ...',;:;;;;,.................
// ,'...................................... ...........';:::;,''.';;;cllc:;:cc::cloolcc:,,;codl:,'';:c::c:;;:cooddolc;,...            ...',,,,,,'......  .......  .
// ,'.................................................';::;'...,:::;,;::::llllllllool:'.....'.....';loc::cllloxdddddooool:,..            .....                     
// ,'.............................................'',,;:,...,;;::,'''',;;;;,'..................,::;;loooolodddddddxdlclloooc;,..                                   
// ,'.....................................  ....':cc,.......''..'','........    ...............,;:;,:coddolodddddoollloooooolcc:'..................................
// ....  .                                   ..',;,................... ......  ..................'''',clolllodddddollllc::clc:cll:;'...............................
//                                    ........'............''........................................',,'''',;:clddllclc:::::cclodoc;..............................
//                   ......................',..........'''....................................................';clollllloolcclllcclol:,............................
// ....................................................''''....................................................';:looollloddollllccllc;,...........................
// .................................................''',,,,''....     ...........................................,;cllllloodddolc::clolc:;,'.......................
// ................................................',,,,,,,'..     ...............................................,;:cloddolllloolllloddolc;'......................
// ..............................................',,,,,,,'..    ...'''........................................'',,;:ccloxkxoc:::cloooolllool:......................
// ............................................',,,;;;;,... ...',;;;'..... ...............................'',;::ccllllodkOOko:;;;,,;:cccodool:'....................
// ..........................................'',,;;;;;;,..',;:::::;'.................................',,;:cclooooooooooddxkkdl:;,....,;clllodl;'...................
// ...................................... ..',,,;::::::::ccllllcc:;,'....................''',,;;;;:::cclloooooooooooooooooooolc;,.......',:ldo:;,...        .......
// ..................................... ...',,;::ccclllllllllllllcccc::c::;;,,,,,;;;::cccllllllloooooooooooooooooooooooolllllcc:,'.....',:lddoll:..         ......
// .......................................'',,;::cclllooollllllllllllllloooollllloooooddddddddddddddooooooooooooooooooooolllllcc::;,,,,,,,;cllccoo:..         .....
// ......... ...  .................... ...'',;;:ccllllllollcccllllllllllllloooodddddddddddddddddddddddddddooooooooooooooooollllccc::;,,;,,,:cc::col;..             
//                ..................   ..''',;::ccccccllllccccclllllllllllloooooddddddddddddddddddddddddddddddoooooooooooooollllccc:;,,;;;:ll:,;coo:'...          .
//                 .................  ..'''',;::::::cccccccccccllllllllllloooooooooooooodddddddddddddxxxxxxxdddoooooooooooooolllllc:;',;;;codl:clooc'...          .
//                 ...............   ...'''',;;:::::ccccccccccccllllllllllooooooooooooooddddoddddddddxxkkkxdddooooooooooooolllllllc:,'''.';llcc::coo:.           ..
//                    ..........     ..''''',,;;:::::ccccccccclcllllllllllloooooooooooooodddddooooddddxxxxddooooooollooollllllllllc;'.....',,;;;;:ll:.           ..
//                        ......    ...''''',,;;;;;::::ccccccllllllllllllllooooooooooooooddddddddddddddddddooooooollllllllllllllcc:,'....',,::;,,;cc;.           ..
//                   ...........   ....'''''',,,;;;;::::ccccccllllllllllllooooooooooooooddddddddddddddddddoooooollllllllllllllcccc:,'..',;;;cl:,,;cc;.......     ..
// .....            ............   .....''''',,,;;;;::::cccccccllllllllllloooooooooooooddddddddddddddddddoooooolllllllllllllllcccc:,...',;;;:ol:,;:c:'.....      ..
// .........      ..............   ....'''''',,,,;;;;::ccccccccccccclllllllloooooooooooooooooddddddddddooooooolllllllllllllllcccc:;'...',,,;:llc::;::'.           .
// .........      .............   ....'''''''',,,,;;:::ccccccccccccccclllllllolloooooooooooooooddddddddooooooolllllllllllllllcccc:,....',,,;:cclol::;'.            
// .........       ...........   ....'''''''',,,,;;;:::cccccccccccccccccclllllllooooooooooooooooodddddoooooooollllllllllllllccccc:,....',,,,:cllolc:;..            
// ..... ...           .....     ...'''''''',,,,,,,;;;:::ccccccccccccccccccllllllloooooooooooooooodddooooooooollllllllllllllccccc:,....'...';:cllccc:..            
//       ..            .....    ...'''''''''.......''',;;;::::cccccccccccccclllllllllllloooooooooooooooooooooollllllllllllllccccc:,.........';:ccllc;.             
//                     ....    ...'''''''.................'',,;::ccccccccccccccccclllllllllllloooooooooooooooollllllllllllccccccc;'....'...',;:cllll:.      .  .   
//                     ....    ..'''''''.....  ...............',;:cccc:::cccccccccccccccllllllllllllllllloooollllllllllllccccccc:,...''..',,;;:clool;.             
//             .      ....    ..''''''..........................',;;;;;::ccc:cccccccccccccclllllllllllllllllllllllllllllllcccccc;'..'''..',,,;;:ldol;......        
//              ....'.....   ..''''''......'',,;;;;;;;,'..........''',,;::::::::::::::::ccccccccccc:::::::::cccc::ccllllllccccc:;'..''''''',,,;cooc;'............  
// ........    ..;;;::,....  .'','''.....''',,,;;;:::::;;,''..........',;;::::::::::::::::::::;;,''.......''',,,,,,;:cllllccccc:;,'..'','',,,,;cll:..............  
// ........     .,,,'..     ..',,,'''...''''.''',,;;;:::;;,,'...........,,;:ccc::::::;;,,,,,,''...............'''''',;:cllcccccc:;...',''';;,,:clc,.............   
// .........    .'''...    ..',,,,'''..''''.............................',;:clccc:::;;,'.............'''''',,,,''....',:cccccccc:;...','',;;,,:cc,.  ...........   
// ..........   ..'...... ...',,,''''.''......              ............';:clllllc:::;,'.......',,;;:cccccccccc::;,'...,:cccccccc;'.''...'',,,;::'.   .  ...   .   
// .........    ..'.....  ..''','''''.....                        . ....,:clloooollcc;'.......',,;;;:ccllllllllllcc:;,.';:ccccccc:,'......''',;c:'.           ..   
//              ..'''... ....''''',,''.....'''.........''''............';cllooooollc:;'..............',;:cclllllccccc;,,;:cccccccc;,'.....',,,;:;.            ..  .
//          .    .''....  ..'''''',,,,'''',,;;;::::::cccccc:::::,,'....,:cloodooollcc:;;,'....          ...';:::ccccc:;;:ccccccccc:,'.....',;;:;'.                 
//          .   ..''...  ...''''',,;;;;,,'..''',,;;::cccllllllllc;,'..';:cloooollllllooolc:,'......         ...,;::ccc:::ccccccccc:;'.....'',:llc,..............   
//         .    ..'....  ...'''',,;;;;::;,''....',;::ccclllllllc;,'''',:cllooollllllloolcccc::;,,,'''............',:cc:::ccccccclc:;'......'';codo:'...........    
//              ......  ....''',,;;;::ccccc:;,'''',,;;;:::ccccc:,''',,;cclloollllllllool:;::::cc:::cccccccccc::;,'',;cccclllllllll:,.......'';cldxxl'              
// .....         ....   ...'''',;;:::ccllllllcc:;;;,,,;;;:ccccc;,,,,,;:cllooolllllllloolc:;;;;::ccccllcccccccccccc:;:clllllllooolc;'.....'',;cllllc;.    ..........
// .......       .... .....''',,;;:::ccclllllloolllllcccclllccc:;;,;;:cclooollllllllllooolc:;,,,,;;:cccccc::cccclllccllllllllllllc;'....',;:clc:;,'................
// .......       .... .....''',,,;:::cccclllllooollllllllllccc:::::::cclloolllllllllloooooollc:;;,,,;;::ccccccccllllllllllllccllc:;''''',;::;,,,,'.................
// ..........    ..........''''',;;:::cccclllllllllllllcc:::;;;;::::cccloolllllllooooooooooooooolllcccccclllllllllllllllllllcccc:;,'.''',;;;;;::,.  .........     .
// ..........    ..............'',;;:::ccccllllllccccc:;,,;:;;;;:::ccclloollllllllooooooooooodooooooooooooooooolllllllllloolccc::,'..'';:ccc:cc,.    ..           .
// .......  ..    ..............'',,;;:::cccccccccc::;,',;cc:;;::ccccclooollllllllllloollllooodddoooooodddddooollllllccllolcc:::,'...',:cllccc;.                   
//          ..    ..'.............''',,;;;::::::::;;;,'';:c::;::cccccllooolllllllllllllll::cloooddoooooooooooooollllcccllolc:::;'.....,;cclll;.                    
//                ..''................'',,;;;;;;,,,,''..',;;;;;:cccclllooolllllllllloollc;'';clloooooooooolloolllllllccclllc::;,'.....,;clll:.                     
//                ..''.................''''''''''''........'''',;::ccllooollcclllloooollc,...';:cllllllllllllllllllllcccccc:::;,''',,,;:clc;.                      
//            .......'.................................  .......,,;:ccclllcccccllllllcc::;'....';:cclllllllllllllllccccccc:::;,',;:cc::clc,.  .....................
//                 ..................................         ....',,;;:;;;,;;;;;;;,;;;;::;,.....,;:ccccccccccccccccccllc:::;;,;::cclllol;.   .....................
//       .          .................. .............            .....'','............,;::::;,.....';::cc::ccccccccccccllcc::;;;:cclllooo:.                         
// ........           ...........',,'..........                    ......        ..'',;;:::;;,.....',;::::::::::::::ccllc:::;::cloolool:.    ......................
// .......            ...........';::,.....        ...                         ...''''',;;;;;,'.....',;;::::;;;;;;;::cccc:::ccclooolc;..    .......................
//                    ............,:c,....        .....   ......       ..........',,'''',,,,,,'.......,;;::::;;;;;::::cccc::clllool;'.        .....................
// ............      .............';c;....            .   .....   ......',,,,,,;;;;;,'''''''''''......';;:::ccc::::::clll:::cloool;.                               
// .......    ..     ..............,:;'.....................    .........'',,,,;;;::;;,,,''',,,,,'....';::cccccccc::ccllc:::cllll,.                                
//             .      ..............','............'''''.......'''..''',,,,,,,,,'''''.'',,,;,,;;;;;,'',:cccllcccccc::clcc:cccclc,.                                 
//             .       .............................''''''',;;:::::::cccccccccc::;,,,'''''.'',;;;:::;;:cccclcccccc::::c::::c:;,.                                   
//                     ...............................''',;:::::ccccccclllllllllllllccccc:,'..',,;;;;:ccccccc:::::;;::::::::,.          ...                        
//                      .................................'',,,,,;;;:::cclllllllllclllllllcc;,'..'',;:c::::::::::;;;,;;;::c:,.        .....                         
//                       ...        ......................''''...'',,,;;::::cccccclllllllllc:,''',:cc:;,,;;;;;;,,,,,;;;:cc:'.                              ......  
//                ...                 ...........................'''',,,,,;;:::ccllllllloollc:;;::c:;;,,;;;;;;,,,,,,,;;::;,..  ..                  ................
//                 .                     .......'''''..............'''''',;::::clllloooooollc::::::;,,,,;;;;,,'''''',;:c;'..........               ................
// .......                               ......',,,,,,''......'''..',,;;;::::cccclllllllllc::;:::;,,,,,,;;;,,,'''.'',;;;,..   ......                ............  .
// ..........                             .....'',,,,,,,,,,,,;;;;,;;::::cccccccc:ccccccccc::;;;;;;,,,,,,,,,,''....'',,....  .........    ....      ................
// .........               ...            ......'',,,,;;;:::ccccccccc::ccllllcc::;;;;;;;::;;;;;,,'',,''',,,'......',,'.......................       ...............
// ................       .....            ......'''',,,;;::ccllllllcccccccccc:;;;;,,,,,;,,,,,,'.......',''......';;,...................                           
// .................        ....            ...',,,'''',;;;;:ccccllllllc::::::;,,;,,'..','......................';::'.  ...... .                                   
// ........  ..  ..         .....          .....'''....''',;:::::::::::::;;;;,,,,,'''''''................ ...'',;:c:.      ..                                      
//              ...         ......            ...........',;;;;;;;;,;;;;;;;,,'''''...''....................',,;;:cl;.                                              
//               ..         ........          ...........',,,,,,,,'',,''',''''''....................  ....',;;::cll;...........................................''''
//                          .........           ............'',,''.',,'..''''''..................    ..'',;;::cclll;.................'''...'''''''.................
// ....................................         ....   ..................''''...... .........      ..',,;;;:cccclol,................   .  .........                
// ......................................                       ..............    .......       ...',,;;;:cccccllol'                                               
// ......................   ...............           .........   ..   . ....                ...',,,;;;::ccclllllol;........................              .........
//                          ................     ...';:cllllool:..                       .....'',,,;;::cccccllllloddlc;'....................                      .
// .............            ..................,;:cclllllllllodxkxl:'.                 .....''',,,;;::cccllllcccllodxdddolcc::;''''...                              
// ..............           ...........',;;:cclloollolllllllllodkkkxo:..         .......'',,,,,;;::ccllllllcccclooddoloddddoooolcccc:,,'...                        
//             .            .....',;:ccllllllloooooooooooolllllloodxkkd:'.........'''',,,,;,;;;::cclllllllccccclodolclooooolllollllllllllcc;.                      
//                          ..,;::ccllllllloooodddooooooolllllllllooddxkdl;'....',;;;;;;;;;::::cclllllllccccllllodlcclllllccccllclllccccccllc,.....        ....    
//                         .';cccccclllllloodooooooolllllccccllllooooodxkkxoc;;;;;;;;;;;;::cccllllllllllcccclllloolcclllcc:::ccccccccccc::cllllcc:;,'.....',;;,'..